<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CodeAnalysisRuleSet>c:\Users\fooba\Projects\Coding\koffing\.vscode\ruleset.xml</CodeAnalysisRuleSet>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="gdUnit4.analyzers" Version="1.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="gdUnit4.api" Version="5.1.0-rc5" />
    <PackageReference Include="gdUnit4.test.adapter" Version="3.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Microsoft.TestPlatform" Version="18.9.0" />
  </ItemGroup>
</Project>