using System.Collections.Generic;
using System.Linq;
using Koffing.Blocks;
using Koffing.Melds;
using Koffing.Tiles;

namespace Koffing.Waits;

/// <summary>
/// An abstract derived <see cref="Block"/> with the semantic meaning of being an "incomplete" part of a hand.
/// </summary>
/// <remarks>
/// A wait is a <see cref="Block"/> that needs additional tiles to be a useful part of a hand, compared to a
/// <see cref="Meld"/>, which does not need any additional tiles, and which a wait would become if it received the
/// correct tiles.
/// </remarks>
public abstract class Wait : Block
{
	/// <summary>
	/// Returns all possible first-level waits from a collection of <see cref="Tile"/>s.
	/// </summary>
	/// <remarks>
	/// A "first-level" wait is a single <see cref="Kanchan"/>, <see cref="Ryanmen"/>, <see cref="Penchan"/>, or
	/// <see cref="PairWait"/> that can be made from <paramref name="tiles"/>. Note that this does not include
	/// <see cref="SevenPairsWait"/>, <see cref="ThirteenOrphansWait"/>, and <see cref="Orphan"/>. These special waits
	/// are only generated by <see cref="Block.GetPossibleBlockSets(IEnumerable{Tile})"/>.
	/// </remarks>
	/// <param name="tiles">
	/// The <see cref="Tile"/>s to use to create <see cref="MadeBlockContext"/>s of first-level waits.
	/// </param>
	/// <returns>
	/// An <see cref="IEnumerable{T}"/> of <see cref="MadeBlockContext"/>s of first-level waits that can be created from
	/// <paramref name="tiles"/>.
	/// </returns>
	public static IEnumerable<MadeBlockContext> GetFirstLevelWaits(IEnumerable<Tile> tiles)
	{
		return PairWait.GetPossible(tiles)
			.Concat(Ryanmen.GetPossible(tiles))
			.Concat(Kanchan.GetPossible(tiles))
			.Concat(Penchan.GetPossible(tiles));
	}

	/// <summary>
	/// Constructor. Optionally takes in an <see cref="IEnumerable{T}"/> of <see cref="Tile"/>s.
	/// </summary>
	/// <remarks>
	/// It's not possible to construct a concrete version of this class as it's <see langword="abstract"/>, but it must
	/// be mentioned that even if you could, it is preferred to use <see cref="IBlock"/> static functions such as
	/// <see cref="IBlock.GetPossible(IEnumerable{Tile})"/>, or the
	/// <see cref="GetFirstLevelWaits(IEnumerable{Tile})"/> static helper function in this class to ensure proper
	/// semantic meanings.
	/// </remarks>
	/// <param name="tiles">The <see cref="Tile"/>s that make up the wait.</param>
	public Wait(IEnumerable<Tile> tiles = null) : base(tiles)
	{
	}
}